---
- name: Deploy Calculator Docker Container
  hosts: localhost
  connection: local
  become: false

  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "28vishesh/calculator"
        source: pull

    - name: Stop existing container if running
      shell: docker stop calculator
      ignore_errors: yes

    - name: Remove existing container if exists
      shell: docker rm calculator
      ignore_errors: yes

    - name: Run new container
      shell: docker run -d --name calculator 28vishesh/calculator
